# These rules are documented on https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

ul: # unordered list style
  style: sublist

line_length: false  # do not check for line length; rely on editor wrapping

no-inline-html:
  allowed_elements:
    - abbr
    - i

emphasis-style:
  style: underscore

strong-style:
  style: asterisk
